from .usuarioSerializer import UsuarioSerializer
from .ubicacionSerializer import UbicacionSerializer
from .alertaSerializer import AlertaSerializer
from .notificacionSerializer import NotificacionSerializer
from .contactoSerializer import ContactoSerializer