# Generated by Django 6.0.4 on 2026-04-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlertNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='AlertNet_usuario',
        ),
    ]
