# Generated by Django 6.0.4 on 2026-04-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlertNet', '0002_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacto',
            table='AlertNet_contacto',
        ),
    ]
